### ISSUE TITLE
AUTOSPOOL Setup updation on User's Workstations

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-Design-Application#12]
Request come from Department to upgrade the Autospool New Version on all user’s Workstations at NOIDA & Chennai Location. New Autospool Setup down load link is available in trailing mail. Please confirm after task completion.

@Isgec/dc-infra-team   , Myself is working for downloading Autospool new version . I will inform to helpdesk team for installation in usser's machines accordinly...

**Comment by msrawat-isgec** [comment]
From: praveen-isgec ***@***.*** 
Sent: Friday, June 11, 2021 3:28 PM
To: Isgec/ITIL-Design-Application
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-Design-Application] AUTOSPOOL Setup updation on User's Workstations (#12)

 

Request come from Department to upgrade the Autospool New Version on all user’s Workstations at NOIDA & Chennai Location. New Autospool Setup down load link is available in trailing mail. Please confirm after task completion.

@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  , Myself is working for downloading Autospool new version . I will inform to helpdesk team for installation in usser's machines accordinly...

**Comment by msrawat-isgec** [comment]
Dear Team,

 

Latest Autospool Application is downloaded and keep it on mentioned
location. 

 

Rajesh Sir, Please share the details of At least one Engineer, First we will
upgrade and test on his machine , if everything will work on that machine
then we will make plan for upgradation of rest of the machines.

 

 

\\192.168.25.55\AUTODESK_2020



If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: ***@***.***
***@***.***> On Behalf Of Rajesh kumar Vashist
Sent: 11 June 2021 09:00
To: ***@***.***; 'Support Team 63'
***@***.***>
Cc: 'Harish Kumar' ***@***.***>; ***@***.***; 'ESG
Pragasam' ***@***.***>; 'saravanan.b'
***@***.***>; 'SOMASUNDARAM' ***@***.***>; Vinay
Sharma ***@***.***>
Subject: Reminder: AUTOSPOOL Setup updation on User's Workstation .

 

Dear Praveen,

 

Please update the status of Action plan for trailing mail. 

 

Thank & Regards,

 

Rajesh Kumar Vashist 

CESC

 



A-56, Sector 63, Noida - 201 301 U.P., India

Mobile : +91 84485 95663

Tel.: +91-120-458 1608

Website:  <http://www.isgec.com/> www.isgec.com

**********************************************************************

Please save paper,to save our planet to live, use both side if u can.

**********************************************************************

 

From: Rajesh kumar Vashist ***@***.*** 
Sent: 09 June 2021 14:50
To: ***@***.*** ***@***.***> ;
'Support Team 63'
Cc: 'Harish Kumar'; ***@***.***'; 'ESG Pragasam'; 'saravanan.b';
'SOMASUNDARAM'; Vinay Sharma ***@***.***
***@***.***> )
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Dear Praveen/Team,

 

Please update the Autospool Version  on all user's Workstations at NOIDA &
Chennai Location. New Autospool Setup down load link is available in
trailing mail. Please confirm after task completion.

 

Thank & Regards,

 

Rajesh Kumar Vashist 

CESC

 



A-56, Sector 63, Noida - 201 301 U.P., India

Mobile : +91 84485 95663

Tel.: +91-120-458 1608

Website:  <http://www.isgec.com/> www.isgec.com

**********************************************************************

Please save paper,to save our planet to live, use both side if u can.

**********************************************************************

 

From: Nilesh ***@***.*** 
Sent: 08 June 2021 10:24
To: Rajesh kumar Vashist; support
Cc: 'Harish Kumar'; ***@***.*** ***@***.***> ;
'saravanan.b'; 'SOMASUNDARAM'
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Dear Sir,

 

Kindly download AUTOSPOOL new setup from below link, below issue has been
resolved please check and revert back.

 

https://parascadd0-my.sharepoint.com/:f:/g/personal/transfer_parascadd_com/E
pzV3MpvyGJDqfY2dkAG12oBTDh5ObD_tzqrSL5a1qJu7w?e=JZpGee
<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fparascadd0-my.sharepoin
t.com%2f%3af%3a%2fg%2fpersonal%2ftransfer_parascadd_com%2fEpzV3MpvyGJDqfY2dk
AG12oBTDh5ObD_tzqrSL5a1qJu7w%3fe%3dJZpGee&c=E,1,u-8nyshrQJ5GeBdBOweI_i5zF33Y
PYRnJFSJHq-HTcYZlJivVCBy4vSogsAfjezQoKld70ah0eRtXLJTt-6ZKbYUXbmEhnu0Eup9hTio
db-1JQ,,&typo=1> 

 

Thanking you and assuring you best of our services always,

With best regards,
Nilesh Dhumale.
---------------------
Paras Cadd Pvt Ltd- Efficient Automation Partner (EAP)
Mumbai -400 086. India : ISO 9001:2015
India: Ph: 0091-22-21015100/25111-111/25111-222

UAE: Parascadd Pvt Ltd Branch- Media City, Sharjah. Ph: +971-(0)58575011
SKYPE : nilesh_parascadd  
 
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.parascadd.com%2f&c=E
,1,lnsWlYhYSc9FC9efIgRSp_jSHtwSnakjhYPnCXpzyKQiReODDF2UikFMlGg0IKMZIa9ORezs8
nglI3DQ7FGbNn-xWB1-4zAtLjYJhbauUK2B8VstuzWB&typo=1> www.parascadd.com ;
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.eurekadsoft.com%2f&c
=E,1,al_fTjTgrVs4v59Y3IlUig_vGr43O87e_fBI57mHoM8wuN7CFPWflii1y7VEwgFkIgefALR
naTLWFF_CDRMI02ZtYnD0sM8C-o5SZGU0&typo=1> www.eurekadsoft.com

 

 

 

From: Rajesh kumar Vashist ***@***.*** 
Sent: Friday, 14 May, 2021 11:20
To: support ***@***.*** ***@***.***> >; Nilesh
***@***.*** ***@***.***> >
Cc: 'Harish Kumar' ***@***.***
***@***.***> >; ***@***.***
***@***.***> ; 'saravanan.b' ***@***.***
***@***.***> >; 'SOMASUNDARAM'
***@***.*** ***@***.***> >
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Attachment added.

 

From: Rajesh kumar Vashist ***@***.*** 
Sent: 14 May 2021 11:19
To: ***@***.*** ***@***.***> ;
***@***.*** ***@***.***> 
Cc: 'Harish Kumar'; ***@***.***'; 'saravanan.b'; 'SOMASUNDARAM'
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Dear Nilesh,

 

Please provide your support for trailing mail error issue. We already book a
ticket on your support centre of web site.

 

 

Thank & Regards,

 

Rajesh Kumar Vashist 

CESC

 



A-56, Sector 63, Noida - 201 301 U.P., India

Mobile : +91 84485 95663

Tel.: +91-120-458 1608

Website:
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.isgec.com%2f&c=E,1,z
69_7VVz7zUhvWTIaDIyXjiNSJknvalusgnZ5ctjMujV_dAiO4H13O5PQ81UItV4YoQkDy06CA7CF
sVk8erH5Yw9GkQ_FW5voWLflXGoOQ-YYh_QRA,,&typo=1> www.isgec.com

**********************************************************************

Please save paper,to save our planet to live, use both side if u can.

**********************************************************************

 

 

 

From: SOMASUNDARAM ***@***.*** 
Sent: 14 May 2021 09:19
To: ***@***.*** ***@***.***> 
Cc: 'Harish Kumar'; ***@***.*** ***@***.***> ;
'saravanan.b'
Subject: AUTOSPOOL DRAWING ISSUES.

 

Dear sir,

I faced some problems while working in Autospool.

The autospool generated drawings BOM not inline with Isometric views.

I have attached the cadison drawing, Autospool drawing, & pcf file.

I have listed the error for your easy reference.

 

Call Log has been raised for this issue. (9839)

 

1. P.No.16 Should come with itemcode IFP010. (P.No.16 comes as separate
itemcode IFP001)

2. P.Nos. 22 & 23 is 2 qty. (1 qty with itemcode IFP008 &  1 qty with IFP012
as per isometric view, but in BOM the 2 qty is assigned to IFP008 Itself.

3. P.Nos. 5 & 19 should come with with itemcode IFP009, as per iso view, but
in BOM p.no.5 is mingled with IFP008.

4. P.no.13 should come with itemcode IFP012 as per iso view, but it is
mingled with IFP008.

 

For drg releasing, I have done these corrections mannualy.

 

Regards,

K.Somasundaram

9884160313

**Comment by msrawat-isgec** [comment]
Please start with my Workstation.

 

Thank & Regards,

 

Rajesh Kumar Vashist 

CESC

 

Isgec eSign

A-56, Sector 63, Noida - 201 301 U.P., India

Mobile : +91 84485 95663

Tel.: +91-120-458 1608

Website:  <http://www.isgec.com/> www.isgec.com

**********************************************************************

Please save paper,to save our planet to live, use both side if u can.

**********************************************************************

 

From: Praveen Kumar ***@***.*** 
Sent: 11 June 2021 18:45
To: 'Support Team 63'; ***@***.***; 'Rajesh kumar Vashist'
Cc: 'Harish Kumar'; ***@***.***; 'ESG Pragasam'; 'saravanan.b';
'SOMASUNDARAM'; 'Vinay Sharma'; 'Dhirendra Singh Bisht';
***@***.***
Subject: RE: Reminder: AUTOSPOOL Setup updation on User's Workstation .

 

Dear Team,

 

Latest Autospool Application is downloaded and keep it on mentioned
location. 

 

Rajesh Sir, Please share the details of At least one Engineer, First we will
upgrade and test on his machine , if everything will work on that machine
then we will make plan for upgradation of rest of the machines.

 

 

\\192.168.25.55\AUTODESK_2020 <file:///\\192.168.25.55\AUTODESK_2020> 



If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: ***@***.***
***@***.***> On Behalf Of Rajesh kumar Vashist
Sent: 11 June 2021 09:00
To: ***@***.***; 'Support Team 63'
***@***.***>
Cc: 'Harish Kumar' ***@***.***>; ***@***.***; 'ESG
Pragasam' ***@***.***>; 'saravanan.b'
***@***.***>; 'SOMASUNDARAM' ***@***.***>; Vinay
Sharma ***@***.***>
Subject: Reminder: AUTOSPOOL Setup updation on User's Workstation .

 

Dear Praveen,

 

Please update the status of Action plan for trailing mail. 

 

Thank & Regards,

 

Rajesh Kumar Vashist 

CESC

 

Isgec eSign

A-56, Sector 63, Noida - 201 301 U.P., India

Mobile : +91 84485 95663

Tel.: +91-120-458 1608

Website:  <http://www.isgec.com/> www.isgec.com

**********************************************************************

Please save paper,to save our planet to live, use both side if u can.

**********************************************************************

 

From: Rajesh kumar Vashist ***@***.*** 
Sent: 09 June 2021 14:50
To: ***@***.***; 'Support Team 63'
Cc: 'Harish Kumar'; ***@***.***'; 'ESG Pragasam'; 'saravanan.b';
'SOMASUNDARAM'; Vinay Sharma ***@***.***)
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Dear Praveen/Team,

 

Please update the Autospool Version  on all user's Workstations at NOIDA &
Chennai Location. New Autospool Setup down load link is available in
trailing mail. Please confirm after task completion.

 

Thank & Regards,

 

Rajesh Kumar Vashist 

CESC

 

Isgec eSign

A-56, Sector 63, Noida - 201 301 U.P., India

Mobile : +91 84485 95663

Tel.: +91-120-458 1608

Website:  <http://www.isgec.com/> www.isgec.com

**********************************************************************

Please save paper,to save our planet to live, use both side if u can.

**********************************************************************

 

From: Nilesh ***@***.*** 
Sent: 08 June 2021 10:24
To: Rajesh kumar Vashist; support
Cc: 'Harish Kumar'; ***@***.***; 'saravanan.b'; 'SOMASUNDARAM'
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Dear Sir,

 

Kindly download AUTOSPOOL new setup from below link, below issue has been
resolved please check and revert back.

 

https://parascadd0-my.sharepoint.com/:f:/g/personal/transfer_parascadd_com/E
pzV3MpvyGJDqfY2dkAG12oBTDh5ObD_tzqrSL5a1qJu7w?e=JZpGee
<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fparascadd0-my.sharepoin
t.com%2f%3af%3a%2fg%2fpersonal%2ftransfer_parascadd_com%2fEpzV3MpvyGJDqfY2dk
AG12oBTDh5ObD_tzqrSL5a1qJu7w%3fe%3dJZpGee&c=E,1,u-8nyshrQJ5GeBdBOweI_i5zF33Y
PYRnJFSJHq-HTcYZlJivVCBy4vSogsAfjezQoKld70ah0eRtXLJTt-6ZKbYUXbmEhnu0Eup9hTio
db-1JQ,,&typo=1> 

 

Thanking you and assuring you best of our services always,

With best regards,
Nilesh Dhumale.
---------------------
Paras Cadd Pvt Ltd- Efficient Automation Partner (EAP)
Mumbai -400 086. India : ISO 9001:2015
India: Ph: 0091-22-21015100/25111-111/25111-222

UAE: Parascadd Pvt Ltd Branch- Media City, Sharjah. Ph: +971-(0)58575011
SKYPE : nilesh_parascadd  
 
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.parascadd.com%2f&c=E
,1,lnsWlYhYSc9FC9efIgRSp_jSHtwSnakjhYPnCXpzyKQiReODDF2UikFMlGg0IKMZIa9ORezs8
nglI3DQ7FGbNn-xWB1-4zAtLjYJhbauUK2B8VstuzWB&typo=1> www.parascadd.com ;
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.eurekadsoft.com%2f&c
=E,1,al_fTjTgrVs4v59Y3IlUig_vGr43O87e_fBI57mHoM8wuN7CFPWflii1y7VEwgFkIgefALR
naTLWFF_CDRMI02ZtYnD0sM8C-o5SZGU0&typo=1> www.eurekadsoft.com

 

 

 

From: Rajesh kumar Vashist ***@***.*** 
Sent: Friday, 14 May, 2021 11:20
To: support ***@***.***>; Nilesh ***@***.***>
Cc: 'Harish Kumar' ***@***.***>; ***@***.***;
'saravanan.b' ***@***.***>; 'SOMASUNDARAM'
***@***.***>
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Attachment added.

 

From: Rajesh kumar Vashist ***@***.*** 
Sent: 14 May 2021 11:19
To: ***@***.***; ***@***.***
Cc: 'Harish Kumar'; ***@***.***'; 'saravanan.b'; 'SOMASUNDARAM'
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Dear Nilesh,

 

Please provide your support for trailing mail error issue. We already book a
ticket on your support centre of web site.

 

 

Thank & Regards,

 

Rajesh Kumar Vashist 

CESC

 

Isgec eSign

A-56, Sector 63, Noida - 201 301 U.P., India

Mobile : +91 84485 95663

Tel.: +91-120-458 1608

Website:
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.isgec.com%2f&c=E,1,z
69_7VVz7zUhvWTIaDIyXjiNSJknvalusgnZ5ctjMujV_dAiO4H13O5PQ81UItV4YoQkDy06CA7CF
sVk8erH5Yw9GkQ_FW5voWLflXGoOQ-YYh_QRA,,&typo=1> www.isgec.com

**********************************************************************

Please save paper,to save our planet to live, use both side if u can.

**********************************************************************

 

 

 

From: SOMASUNDARAM ***@***.*** 
Sent: 14 May 2021 09:19
To: ***@***.***
Cc: 'Harish Kumar'; ***@***.***; 'saravanan.b'
Subject: AUTOSPOOL DRAWING ISSUES.

 

Dear sir,

I faced some problems while working in Autospool.

The autospool generated drawings BOM not inline with Isometric views.

I have attached the cadison drawing, Autospool drawing, & pcf file.

I have listed the error for your easy reference.

 

Call Log has been raised for this issue. (9839)

 

1. P.No.16 Should come with itemcode IFP010. (P.No.16 comes as separate
itemcode IFP001)

2. P.Nos. 22 & 23 is 2 qty. (1 qty with itemcode IFP008 &  1 qty with IFP012
as per isometric view, but in BOM the 2 qty is assigned to IFP008 Itself.

3. P.Nos. 5 & 19 should come with with itemcode IFP009, as per iso view, but
in BOM p.no.5 is mingled with IFP008.

4. P.no.13 should come with itemcode IFP012 as per iso view, but it is
mingled with IFP008.

 

For drg releasing, I have done these corrections mannualy.

 

Regards,

K.Somasundaram

9884160313

**Comment by msrawat-isgec** [comment]
Dear Sir,

 

Given Autos pool application is not working having some issues. Please
coordinate with vender for provide new Application accordingly.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Praveen Kumar ***@***.***> 
Sent: 11 June 2021 18:45
To: 'Support Team 63' ***@***.***>;
***@***.***' ***@***.***>; 'Rajesh kumar
Vashist' ***@***.***>
Cc: 'Harish Kumar' ***@***.***>; ***@***.***'
***@***.***>; 'ESG Pragasam' ***@***.***>;
'saravanan.b' ***@***.***>; 'SOMASUNDARAM'
***@***.***>; 'Vinay Sharma' ***@***.***>;
'Dhirendra Singh Bisht' ***@***.***>;
***@***.***'
***@***.***>
Subject: RE: Reminder: AUTOSPOOL Setup updation on User's Workstation .

 

Dear Team,

 

Latest Autospool Application is downloaded and keep it on mentioned
location. 

 

Rajesh Sir, Please share the details of At least one Engineer, First we will
upgrade and test on his machine , if everything will work on that machine
then we will make plan for upgradation of rest of the machines.

 

 

\\192.168.25.55\AUTODESK_2020 <file://192.168.25.55/AUTODESK_2020> 



If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.*** ***@***.***> 

website: www.isgec.com <http://www.isgec.com> 

Mobile:  +91 8448595785

 

From: ***@***.***
***@***.***>
***@***.***
***@***.***> > On Behalf Of Rajesh kumar
Vashist
Sent: 11 June 2021 09:00
To: ***@***.*** ***@***.***> ;
'Support Team 63' ***@***.***
***@***.***> >
Cc: 'Harish Kumar' ***@***.***
***@***.***> >; ***@***.***
***@***.***> ; 'ESG Pragasam' ***@***.***
***@***.***> >; 'saravanan.b' ***@***.***
***@***.***> >; 'SOMASUNDARAM'
***@***.*** ***@***.***> >; Vinay
Sharma ***@***.*** ***@***.***> >
Subject: Reminder: AUTOSPOOL Setup updation on User's Workstation .

 

Dear Praveen,

 

Please update the status of Action plan for trailing mail. 

 

Thank & Regards,

 

Rajesh Kumar Vashist 

CESC

 



A-56, Sector 63, Noida - 201 301 U.P., India

Mobile : +91 84485 95663

Tel.: +91-120-458 1608

Website:  <http://www.isgec.com/> www.isgec.com

**********************************************************************

Please save paper,to save our planet to live, use both side if u can.

**********************************************************************

 

From: Rajesh kumar Vashist ***@***.*** 
Sent: 09 June 2021 14:50
To: ***@***.*** ***@***.***> ;
'Support Team 63'
Cc: 'Harish Kumar'; ***@***.***'; 'ESG Pragasam'; 'saravanan.b';
'SOMASUNDARAM'; Vinay Sharma ***@***.***
***@***.***> )
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Dear Praveen/Team,

 

Please update the Autospool Version  on all user's Workstations at NOIDA &
Chennai Location. New Autospool Setup down load link is available in
trailing mail. Please confirm after task completion.

 

Thank & Regards,

 

Rajesh Kumar Vashist 

CESC

 



A-56, Sector 63, Noida - 201 301 U.P., India

Mobile : +91 84485 95663

Tel.: +91-120-458 1608

Website:  <http://www.isgec.com/> www.isgec.com

**********************************************************************

Please save paper,to save our planet to live, use both side if u can.

**********************************************************************

 

From: Nilesh ***@***.*** 
Sent: 08 June 2021 10:24
To: Rajesh kumar Vashist; support
Cc: 'Harish Kumar'; ***@***.*** ***@***.***> ;
'saravanan.b'; 'SOMASUNDARAM'
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Dear Sir,

 

Kindly download AUTOSPOOL new setup from below link, below issue has been
resolved please check and revert back.

 

https://parascadd0-my.sharepoint.com/:f:/g/personal/transfer_parascadd_com/E
pzV3MpvyGJDqfY2dkAG12oBTDh5ObD_tzqrSL5a1qJu7w?e=JZpGee
<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fparascadd0-my.sharepoin
t.com%2f%3af%3a%2fg%2fpersonal%2ftransfer_parascadd_com%2fEpzV3MpvyGJDqfY2dk
AG12oBTDh5ObD_tzqrSL5a1qJu7w%3fe%3dJZpGee&c=E,1,u-8nyshrQJ5GeBdBOweI_i5zF33Y
PYRnJFSJHq-HTcYZlJivVCBy4vSogsAfjezQoKld70ah0eRtXLJTt-6ZKbYUXbmEhnu0Eup9hTio
db-1JQ,,&typo=1> 

 

Thanking you and assuring you best of our services always,

With best regards,
Nilesh Dhumale.
---------------------
Paras Cadd Pvt Ltd- Efficient Automation Partner (EAP)
Mumbai -400 086. India : ISO 9001:2015
India: Ph: 0091-22-21015100/25111-111/25111-222

UAE: Parascadd Pvt Ltd Branch- Media City, Sharjah. Ph: +971-(0)58575011
SKYPE : nilesh_parascadd  
 
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.parascadd.com%2f&c=E
,1,lnsWlYhYSc9FC9efIgRSp_jSHtwSnakjhYPnCXpzyKQiReODDF2UikFMlGg0IKMZIa9ORezs8
nglI3DQ7FGbNn-xWB1-4zAtLjYJhbauUK2B8VstuzWB&typo=1> www.parascadd.com ;
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.eurekadsoft.com%2f&c
=E,1,al_fTjTgrVs4v59Y3IlUig_vGr43O87e_fBI57mHoM8wuN7CFPWflii1y7VEwgFkIgefALR
naTLWFF_CDRMI02ZtYnD0sM8C-o5SZGU0&typo=1> www.eurekadsoft.com

 

 

 

From: Rajesh kumar Vashist ***@***.*** 
Sent: Friday, 14 May, 2021 11:20
To: support ***@***.*** ***@***.***> >; Nilesh
***@***.*** ***@***.***> >
Cc: 'Harish Kumar' ***@***.***
***@***.***> >; ***@***.***
***@***.***> ; 'saravanan.b' ***@***.***
***@***.***> >; 'SOMASUNDARAM'
***@***.*** ***@***.***> >
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Attachment added.

 

From: Rajesh kumar Vashist ***@***.*** 
Sent: 14 May 2021 11:19
To: ***@***.*** ***@***.***> ;
***@***.*** ***@***.***> 
Cc: 'Harish Kumar'; ***@***.***'; 'saravanan.b'; 'SOMASUNDARAM'
Subject: RE: AUTOSPOOL DRAWING ISSUES.

 

Dear Nilesh,

 

Please provide your support for trailing mail error issue. We already book a
ticket on your support centre of web site.

 

 

Thank & Regards,

 

Rajesh Kumar Vashist 

CESC

 



A-56, Sector 63, Noida - 201 301 U.P., India

Mobile : +91 84485 95663

Tel.: +91-120-458 1608

Website:
<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.isgec.com%2f&c=E,1,z
69_7VVz7zUhvWTIaDIyXjiNSJknvalusgnZ5ctjMujV_dAiO4H13O5PQ81UItV4YoQkDy06CA7CF
sVk8erH5Yw9GkQ_FW5voWLflXGoOQ-YYh_QRA,,&typo=1> www.isgec.com

**********************************************************************

Please save paper,to save our planet to live, use both side if u can.

**********************************************************************

 

 

 

From: SOMASUNDARAM ***@***.*** 
Sent: 14 May 2021 09:19
To: ***@***.*** ***@***.***> 
Cc: 'Harish Kumar'; ***@***.*** ***@***.***> ;
'saravanan.b'
Subject: AUTOSPOOL DRAWING ISSUES.

 

Dear sir,

I faced some problems while working in Autospool.

The autospool generated drawings BOM not inline with Isometric views.

I have attached the cadison drawing, Autospool drawing, & pcf file.

I have listed the error for your easy reference.

 

Call Log has been raised for this issue. (9839)

 

1. P.No.16 Should come with itemcode IFP010. (P.No.16 comes as separate
itemcode IFP001)

2. P.Nos. 22 & 23 is 2 qty. (1 qty with itemcode IFP008 &  1 qty with IFP012
as per isometric view, but in BOM the 2 qty is assigned to IFP008 Itself.

3. P.Nos. 5 & 19 should come with with itemcode IFP009, as per iso view, but
in BOM p.no.5 is mingled with IFP008.

4. P.no.13 should come with itemcode IFP012 as per iso view, but it is
mingled with IFP008.

 

For drg releasing, I have done these corrections mannualy.

 

Regards,

K.Somasundaram

9884160313
