### ISSUE TITLE
Advance steel and Inventor both licence required in my system- Abhishek Bhardwaj (2349)

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-Design-Application#6]
Dear sir,
      In my system advance steel 2018 already installed. Please give me advance steel license and inventor also required. Inventor already install & working condition.

Emp. CODE -2349
IP –  17.61

Thanks & Regards,

Abhishek Bhardwaj
Design

@Isgec/dc-infra-team  , Myself Praveen Kumaris working for the same.

**Comment by bhupender-isgec** [comment]
From: praveen-isgec ***@***.***> 
Sent: 19 March 2021 16:37
To: Isgec/ITIL-Design-Application ***@***.***>
Cc: Bhupender K Kashyap ***@***.***>; Team mention ***@***.***>
Subject: [Isgec/ITIL-Design-Application] Advance steel and Inventor both licence required in my system- Abhishek Bhardwaj (2349) (#6)

 

Dear sir,
In my system advance steel 2018 already installed. Please give me advance steel license and inventor also required. Inventor already install & working condition.

Emp. CODE -2349
IP – 17.61

Thanks & Regards,

Abhishek Bhardwaj
Design

@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  , Myself Praveen Kumaris working for the same.

**Comment by msrawat-isgec** [comment]
From: praveen-isgec ***@***.*** 
Sent: Friday, March 19, 2021 4:37 PM
To: Isgec/ITIL-Design-Application
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-Design-Application] Advance steel and Inventor both licence required in my system- Abhishek Bhardwaj (2349) (#6)

 

Dear sir,
In my system advance steel 2018 already installed. Please give me advance steel license and inventor also required. Inventor already install & working condition.

Emp. CODE -2349
IP – 17.61

Thanks & Regards,

Abhishek Bhardwaj
Design

@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  , Myself Praveen Kumaris working for the same.

**Comment by praveen-isgec** [comment]
Dear Mr. Abhishek,

 

Now both PDMC and AEC licenses are activate I your account.

 

Now you are able open Advanced Steel besides Autodesk Inventor.. Please
check.

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: ***@***.***
***@***.***> On Behalf Of Abhishek Bhardwaj
Sent: 19 March 2021 14:26
To: 'Praveen Kumar' ***@***.***>; 'Support Team 63'
***@***.***>
Cc: 'Konark Jain' ***@***.***>; 'Harish Kaushik'
***@***.***>; 'vinay sharma' ***@***.***>
Subject: RE: Advance steel and inventor both licence required in my system

 

Dear sir,

   Both software required advance steel & inventor. Now inventor not
working. 

 

From: Praveen Kumar ***@***.*** 
Sent: 19 March 2021 14:09
To: 'Support Team 63'
Cc: 'Konark Jain'; 'Harish Kaushik'; 'Abhishek Bhardwaj'; 'vinay sharma'
Subject: RE: Advance steel and inventor both licence required in my system

 

Hi Team,

 

License is activated.  Kindly configure accordingly in Mr. Abhishek
Bhardwaj's machine.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.*** ***@***.***> 

website: www.isgec.com <http://www.isgec.com> 

Mobile:  +91 8448595785

 

From: ***@***.***
***@***.***>
***@***.***
***@***.***> > On Behalf Of Harish Kaushik
Sent: 19 March 2021 10:30
To: ***@***.*** ***@***.***> 
Cc: 'Konark Jain' ***@***.*** ***@***.***>
>; 'Support Team 63' ***@***.***
***@***.***> >; 'Abhishek Bhardwaj'
***@***.*** ***@***.***> >
Subject: RE: Advance steel and inventor both licence required in my system

 

Dear Praveen,

 

Please activate.

 

Thanks & Regards,

Harish Kaushik

 

From: Abhishek Bhardwaj ***@***.***
***@***.***> > 
Sent: 19 March 2021 10:17
To: 'Support Team 63' ***@***.***
***@***.***> >; ***@***.***
***@***.***> 
Cc: 'Konark Jain' ***@***.*** ***@***.***>
>; 'harish kumar' ***@***.***
***@***.***> >
Subject: Advance steel and inventor both licence required in my system

 

Dear sir,

      In my system advance steel 2018 already installed. Please give me
advance steel license and inventor also required. Inventor already install &
working condition.

 

Emp. CODE -2349

IP -  17.61

 

Thanks & Regards,

 

Abhishek Bhardwaj

Design

 




A-56, Sector-63,NOIDA-201 301, U.P., India.

Office No. +91 120 4581567

E-mail:  ***@***.***> ***@***.***

Website:  <http://www.isgec.com/> www.isgec.com

**Comment by praveen-isgec** [comment]
@dhirendra-isgec  , DSB Please close this call.

**Comment by dhirendra-isgec** [comment]
Installation done on user request not seen any approval on this
